travis:
  secure:
    BINSTAR_TOKEN: ns7VEEG0BaIimwC9F8hgBGPT6jksVqyO+KkQY71/kkV6UgbPoDNdbSPdIGSemjL6Nn68/OeJuj2Uog5grNGyfXX0w7M+X3NFZ/xMTeXM0+s7JbBonDCZQOzQ8dlFE0BNWkZyENIwtoX2Tj7l5yeCynYdjR/QKuaBJm0+CoEiPyIHOtRqCJIxZKyxLUP1EoWrKBtNAhqt8VrppnJY2fY9BFideP/hWTavQk3ltmJk4/A6Bsb19WfmgsT1WDallBF7K+KPEuthEJJPiXLVPdoUKz7NkBu1r578y/MRUROEwMxsUquRjop5hPJHq3iTnqqXIlcdxXJdddz5epX6RawRkyE94ltNKhvz5DeCggXMyiMVOcnSepnIEp6STcHbnzijbc0fZVEuoSYag8zyYe/v17aleT+s5LQ73Ls4afPBoJQSmnrayvyhIfBZDxQ0fQHO+4Hac7yBBLwdL9VQOihcbs4MLrSDFpEUvNI51AaEGAxBBy8vN5lkS3UQPR3/dQwHCssFi9d6289zp7klgKLQX9Sy0TeTMLnOzW5zVe3ZtGW+NTvC9YmVX2ciFpkw0fyPjioIlo23OZoDdhxa2xr18XxFioXE72hawT9GPKhV8N31tdW0eDqSpRoTo02cqmT5m/nWBk/MPlJClEJv34sLyue3gn9IdRRV6ZhHHbe2+Q0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
