travis:
  secure:
    BINSTAR_TOKEN: l4THa28vQlLo1yFl0z0Lha2MY22Ln517dbtwDZB47H47Lig1A8n8psaG9ACH0U/Ni0x1WM+zTpkUKJc/zFKlVWKhb5i8WMrnWCKktIgS2OeAwPovEElODUT2+Uc7qpUWTXW2CZuzVe/lMfxLIympRkEUaLRmVucN4L5N7urcnjPIF2jLdapFC0YUY2O+qyTxv22eXWdfKJCN3Q/6OQaYJs1xcwBN7UCqO1DFsqSv7kaD74301JjwNu6L8tzJgyoWJHXnkPeHVI7LIstVyyeRm23HkLyr8mFZyAZ/4pMl//+bq0NgAWSkCJCMzYRlcVZeWrrORuBflky5P8DMgyT1HNpSYUPECV3LhthU48D7oLYOzDuPLM5BsWgYaZFVG9qyYOmvperICmDbNfH/i9TN1uOrL38tK8C4CnFyNcRoYqNH8hElZ49wVZv7rnpbeHf2FlQP+VzoHHCE9fCZ4pfRGhwYeeglxs9PLcmefI2Mw5IasqdmVU6IxYeivf3Q7xOIa54X7ON3cJJoIDrB7DkRCJXPqEfLdDTvcnRfKLjXpeon1YxULiDTVLRHxDCWt9LRyMKtvuoKKkQjNGYpl6eYG05j9GIXZlvbszwPS2iDkrYXuyPKJ36ZmyTDlXJpRODrTjw0Mi4y+2L6yk4rRcbX35BjErnHEKqznQmZJfIFQWo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
